---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama
  namespace: ai
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
  storageClassName: openebs-zfs-1m
