---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunesynctool
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tunesynctool-secret
  data:
    - secretKey: SPOTIFY_CLIENT_ID
      remoteRef:
        key: spotify
        property: CLIENT_ID
    - secretKey: SPOTIFY_CLIENT_SECRET
      remoteRef:
        key: spotify
        property: CLIENT_SECRET
    - secretKey: PLEX_TOKEN
      remoteRef:
        key: plex
        property: TOKEN
    - secretKey: ND_USER
      remoteRef:
        key: navidrome
        property: SYNC_TO_USER
    - secretKey: ND_PASS
      remoteRef:
        key: navidrome
        property: SYNC_TO_PASS
