---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: esphome-secret
    template:
      data:
        secrets.yaml: |
          wifi_ssid: "{{ .WIFI_SSID }}"
          wifi_password: "{{ .WIFI_PASS }}"
          api_key: "{{ .API_KEY }}"
          ota_password: "{{ .OTA_PASS }}"
  dataFrom:
    - extract:
        key: esphome
