---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: idm-tls
spec:
  secretName: idm-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "idm.${SECRET_DOMAIN}"
  dnsNames:
    - "idm.${SECRET_DOMAIN}"
  duration: 160h
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  usages:
    - digital signature
    - server auth
