---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: network
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: k8s-gateway
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: k8s-gateway
    domain: "${SECRET_DOMAIN}"
    ttl: 1
    service:
      type: LoadBalancer
      port: 53
      annotations:
        lbipam.cilium.io/ips: "${K8S_GATEWAY_IP}"
      externalTrafficPolicy: Cluster
    watchedResources: [Ingress, Service]
    serviceAccount:
      create: true
      name: k8s-gateway
    rbac:
      create: false # We create our own minimal RBAC
