---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-gateway
rules:
  # Core resources that k8s-gateway watches
  - apiGroups: [""]
    resources:
      - services
      - endpoints
      - namespaces
    verbs: ["get", "list", "watch"]

  # Ingress resources (your main use case)
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]

  # Events for troubleshooting
  - apiGroups: [""]
    resources:
      - events
    verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-gateway
subjects:
  - kind: ServiceAccount
    name: k8s-gateway
    namespace: network
