---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: talos-shutdown
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: talos-shutdown-secret
    template:
      data:
        WEBHOOK_TOKEN: "{{ .WEBHOOK_TOKEN }}"
        config: "{{ .talosconfig }}"
  dataFrom:
    - extract:
        key: talos-shutdown
