---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nut-server-ups-a
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nut-server-ups-a-secret
    template:
      data:
        API_PASSWORD: "{{ .API_PASSWORD }}"
        upsd.users: |
          [upsmon]
            password = {{ .API_PASSWORD }}
            upsmon primary
  dataFrom:
    - extract:
        key: nut
