---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teslamate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: teslamate-secret
    template:
      data:
        ENCRYPTION_KEY: "{{ .TESLAMATE_ENCRYPTION_KEY }}"
        DATABASE_USER: &dbUser "{{ .TESLAMATE_POSTGRES_USER }}"
        DATABASE_PASS: &dbPass "{{ .TESLAMATE_POSTGRES_PASS }}"
        DATABASE_NAME: &dbName teslamate
        DATABASE_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        DATABASE_PORT: "5432"
        MQTT_HOST: mosquitto.default.svc.cluster.local
        MQTT_PORT: "1883"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .CNPG_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: postgres
        TESLA_CLIENT_ID: "{{ .TESLAMATE_TESLA_CLIENT_ID }}"
        TESLA_CLIENT_SECRET: "{{ .TESLAMATE_TESLA_CLIENT_SECRET }}"
        TESLA_AUTH_CLIENT_ID: "{{ .TESLAMATE_TESLA_CLIENT_ID }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
      rewrite:
        - regexp:
            source: "(.*)"
            target: "CNPG_$1"
    - extract:
        key: teslamate
      rewrite:
        - regexp:
            source: "(.*)"
            target: "TESLAMATE_$1"
