---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app teslamate
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  values:
    controllers:
      teslamate:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18@sha256:6fa1f331cddd2eb0b6afa7b8d3685c864127a81ab01c3d9400bc3ff5263a51cf
            envFrom: &envFrom
              - secretRef:
                  name: teslamate-secret
          init-extensions:
            image:
              repository: ghcr.io/cloudnative-pg/postgresql
              tag: "16.9@sha256:4418a66c2232ba0bd63dd6c7a98ee401bcac340efbb5f380f8879d004654a7d3"
            command: ["sh", "-c"]
            args:
              - |
                PGPASSWORD="$INIT_POSTGRES_SUPER_PASS" psql -h "$DATABASE_HOST" -U postgres -d "$DATABASE_NAME" \
                  -c "CREATE EXTENSION IF NOT EXISTS cube WITH SCHEMA public;" \
                  -c "CREATE EXTENSION IF NOT EXISTS earthdistance WITH SCHEMA public;" \
                  -c "ALTER FUNCTION ll_to_earth SET search_path = public;" \
                  -c "ALTER FUNCTION earth() OWNER TO $DATABASE_USER;" \
                  -c "ALTER FUNCTION earth_box(earth, float8) OWNER TO $DATABASE_USER;" \
                  -c "ALTER FUNCTION earth_distance(earth, earth) OWNER TO $DATABASE_USER;" \
                  -c "ALTER FUNCTION gc_to_sec(float8) OWNER TO $DATABASE_USER;" \
                  -c "ALTER FUNCTION latitude(earth) OWNER TO $DATABASE_USER;" \
                  -c "ALTER FUNCTION longitude(earth) OWNER TO $DATABASE_USER;" \
                  -c "ALTER FUNCTION ll_to_earth(float8, float8) OWNER TO $DATABASE_USER;" \
                  -c "ALTER FUNCTION sec_to_gc(float8) OWNER TO $DATABASE_USER;"
            envFrom: *envFrom
        containers:
          app:
            image:
              repository: teslamate/teslamate
              tag: 3.0.0@sha256:f064d5b303a98b3ae72d26dac2e7a4adfa67d40c33a2f08f3cc1348d7494cd33
            env:
              TZ: ${TIMEZONE}
              PORT: &port 80
              DISABLE_MQTT: "false"
              TESLA_API_HOST: https://api.myteslamate.com
              TESLA_AUTH_HOST: https://api.myteslamate.com
              TESLA_AUTH_PATH: /api/oauth2/v3
              TESLA_WSS_HOST: wss://streaming.myteslamate.com
              TESLA_WSS_TLS_ACCEPT_INVALID_CERTS: "true"
              TESLA_WSS_USE_VIN: "true"
            envFrom: *envFrom
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health_check
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https

    persistence:
      tmp:
        type: emptyDir
