---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app teslamate
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  values:
    controllers:
      teslamate:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18
            envFrom: &envFrom
              - secretRef:
                  name: teslamate-secret
          init-extensions:
            image:
              repository: ghcr.io/cloudnative-pg/postgresql
              tag: "16.9"
            command: ["sh", "-c"]
            args:
              - |
                PGPASSWORD="$INIT_POSTGRES_SUPER_PASS" psql -h "$DATABASE_HOST" -U postgres -d "$DATABASE_NAME" -c "CREATE EXTENSION IF NOT EXISTS cube WITH SCHEMA public;" -c "CREATE EXTENSION IF NOT EXISTS earthdistance WITH SCHEMA public;"
            envFrom: *envFrom
        containers:
          app:
            image:
              repository: teslamate/teslamate
              tag: 3.0.0@sha256:f064d5b303a98b3ae72d26dac2e7a4adfa67d40c33a2f08f3cc1348d7494cd33
            env:
              TZ: ${TIMEZONE}
              PORT: &port 80
              DISABLE_MQTT: "false"
            envFrom: *envFrom
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health_check
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https

    persistence:
      tmp:
        type: emptyDir
