qbt:
  host: qbittorrent.media.svc.cluster.local
  user:
  pass:

settings:
  force_auto_tmm: true
  force_auto_tmm_ignore_tags:
    - Upload
    - cross-seed
  tracker_error_tag: issue
  nohardlinks_tag: noHL
  share_limits_tag: ~share_limit
  share_limits_min_seeding_time_tag: MinSeedTimeNotReached
  share_limits_min_num_seeds_tag: MinSeedsNotMet
  share_limits_last_active_tag: LastActiveLimitNotReached
  cross_seed_tag: cross-seed
  cat_filter_completed: true
  share_limits_filter_completed: true
  tag_nohardlinks_filter_completed: true
  cat_update_all: true
  disable_qbt_default_share_limits: true

directory:
  root_dir: /data/torrents
  remote_dir: /data/torrents
  recycle_bin: /data/torrents/.RecycleBin
  torrents_dir: /qbittorrent/qBittorrent/BT_backup
  orphaned_dir: /data/torrents/orphaned_data
  cross_seed:

cat:
  movies: /data/torrents/movies
  series: /data/torrents/series
  animemovies: /data/torrents/animemovies
  animeseries: /data/torrents/animeseries
  kidsmovies: /data/torrents/kidsmovies
  kidsseries: /data/torrents/kidsseries
  books: /data/torrents/books
  audiobooks: /data/torrents/audiobooks
  music: /data/torrents/music
  motor: /data/torrents/motor
  sport: /data/torrents/sport
  sportseries: /data/torrents/sportseries
  usedforseeding: /data/torrents/usedforseeding

tracker: { { .QBITMANAGE_TRACKERS | nindent 2 } }

nohardlinks:
  - movies:
      exclude_tags:
        - MaM
  - series:
      exclude_tags:
        - MaM

share_limits:
  noHL:
    priority: 5
    exclude_any_tags:
      - other
    include_all_tags:
      - noHL
    last_active: 2h
    max_seeding_time: 90d
    max_ratio: 10
    cleanup: true

recyclebin:
  enabled: true
  empty_after_x_days: 3
  save_torrents: false
  split_by_category: false
  max_orphaned_files_to_delete: 300

orphaned:
  empty_after_x_days: 3
  exclude_patterns:
    - "**/.DS_Store"
    - "**/Thumbs.db"
    - "**/@eaDir"
    - "**/*.!qB"
    - "**/*_unpackerred"
    - /data/torrents/temp/**
    - /data/torrents/completed/**
    - /data/torrents/cross-seed/**
    - /data/torrents/usedforseeding/**
    - /data/torrents/links/**
  max_orphaned_files_to_delete: 300

notifiarr:
  apikey: "{{ .NOTIFIARR_QBITMANAGE_API_KEY }}"
  instance:

webhooks:
  error: notifiarr
  run_start: notifiarr
  run_end: notifiarr
  function:
    recheck: notifiarr
    cat_update: notifiarr
    tag_update: notifiarr
    rem_unregistered: notifiarr
    tag_tracker_error: notifiarr
    rem_orphaned: notifiarr
    tag_nohardlinks: notifiarr
    share_limits: notifiarr
    cleanup_dirs: notifiarr
