---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: searxng-secret
    template:
      data:
        SEARXNG_SECRET: "{{ .SEARXNG_SECRET }}"
        SEARXNG_REDIS_URL: "redis://dragonfly.database.svc.cluster.local:6379/12"
  dataFrom:
    - extract:
        key: searxng
