---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: authelia-auth
  namespace: network
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-external
  extAuth:
    headersToExtAuth:
      - Cookie
      - Authorization
      - Proxy-Authorization
      - Accept
      - X-Forwarded-For
      - X-Forwarded-Proto
      - X-Forwarded-Host
      - X-Forwarded-Uri
      - X-Forwarded-Method
    http:
      backendRefs:
        - name: authelia
          namespace: default
          port: 80
      path: /api/authz/ext-authz
      headersToBackend:
        - Authorization
        - Proxy-Authorization
        - Cookie
        - Accept
        - X-Forwarded-Method
        - X-Forwarded-Proto
        - X-Forwarded-Host
        - X-Forwarded-Uri
        - X-Forwarded-For

