---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud
spec:
  timeout: 15m
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: nextcloud
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      flavor: fpm-alpine
      # renovate: datasource=docker depName=nextcloud
      tag: 32.0.0-fpm-alpine
    nginx:
      enabled: true

    phpClientHttpsFix:
      enabled: true
      protocol: https

    nextcloud:
      extraInitContainers:
        - name: init-db
          image: ghcr.io/home-operations/postgres-init:17
          envFrom:
            - secretRef:
                name: nextcloud-secret

      extraEnv:
        - name: REDIS_HOST
          value: dragonfly.database.svc.cluster.local.
        - name: REDIS_HOST_PORT
          value: "6379"
        - name: PHP_MEMORY_LIMIT
          value: "8G"
        - name: PHP_UPLOAD_LIMIT
          value: "16G"
        - name: PHP_POST_MAX_SIZE
          value: "16G"

      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: NEXTCLOUD_USERNAME
        passwordKey: NEXTCLOUD_PASSWORD
        smtpUsernameKey: SMTP_USER
        smtpPasswordKey: SMTP_PASS
        smtpHostKey: SMTP_HOST

      host: cloud.${SECRET_DOMAIN}
      containerPort: 80

      mail:
        enabled: true
        fromAddress: ${SECRET_USERNAME}
        domain: gmail.com
        smtp:
          host: smtp.gmail.com
          port: 465
          authtype: LOGIN
          secure: ssl

      lifecycle:
        postStartCommand:
          - "/bin/sh"
          - "-c"
          - |
            su -s /bin/sh www-data -c 'php occ db:add-missing-indices' || true
            su -s /bin/sh www-data -c 'php occ maintenance:repair --include-expensive' || true
            su -s /bin/sh www-data -c 'php occ files:scan --all' || true

      phpConfigs:
        www.conf: |
          [www]
          user = www-data
          group = www-data
          listen = 127.0.0.1:9000
          pm = dynamic
          pm.max_children = 50
          pm.start_servers = 12
          pm.min_spare_servers = 6
          pm.max_spare_servers = 18

      configs:
        logging.config.php: |-
          <?php
          $CONFIG = array (
            'log_type' => 'file',
            'logfile' => 'nextcloud.log',
            'loglevel' => 1,
            'logdateformat' => 'F d, Y H:i:s'
            );
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.96.0.0/16',
              2 => '10.69.0.0/16',
            ),
            'trusted_domains' => array(
              0 => '127.0.0.1',
              1 => 'cloud.${SECRET_DOMAIN}',
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          );
        ingress.config.php: |-
          <?php
          $CONFIG = array (
            'overwrite.cli.url' => 'https://cloud.${SECRET_DOMAIN}',
            'overwriteprotocol' => 'https',
          );
        misc.config.php: |-
          <?php
          $CONFIG = array (
            'default_phone_region' => 'SE',
            'maintenance_window_start' => 1,
          );
        preview.config.php: |-
          <?php
          $CONFIG = array (
            'enabledPreviewProviders' => array(
              'OC\Preview\PNG',
              'OC\Preview\JPEG',
              'OC\Preview\GIF',
              'OC\Preview\BMP',
              'OC\Preview\XBitmap',
              'OC\Preview\MP3',
              'OC\Preview\TXT',
              'OC\Preview\MarkDown',
              'OC\Preview\OpenDocument',
              'OC\Preview\Krita',
              'OC\Preview\HEIC',
            ),
          );

    deploymentAnnotations:
      reloader.stakater.com/auto: "true"

    internalDatabase:
      enabled: false

    externalDatabase:
      enabled: true
      type: postgresql
      host: postgres16-rw.database.svc.cluster.local:5432
      database: *app
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: INIT_POSTGRES_USER
        passwordKey: INIT_POSTGRES_PASS

    ingress:
      enabled: true
      className: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        nginx.ingress.kubernetes.io/proxy-body-size: "16G"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/configuration-snippet: |-
          more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload";
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;
          rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
          rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
          rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
          rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
          location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
          }
          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
          }
          location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
            deny all;
          }
      path: /
      pathType: Prefix

    persistence:
      enabled: true
      existingClaim: *app

    cronjob:
      enabled: true

    startupProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 10
      successThreshold: 1

    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 4
        memory: 8Gi
