directory: /data/media/musik
library: /config/library.db

import:
  write: no
  copy: no
  move: no
  link: no
  hardlink: yes
  resume: yes
  incremental: yes
  quiet_fallback: skip
  log: /config/import.log

paths:
  default: $albumartist/$album%aunique{}%if{$year, ($year)}/$track - $title
  singleton: $artist/Non-Album/$title
  comp: Various Artists/$album%aunique{}%if{$year, ($year)}/$track - $title

per_disc_numbering: yes
original_date: yes

plugins: musicbrainz web fromfilename fetchart chroma duplicates edit

web:
  host: 0.0.0.0
  port: 8337

fetchart:
  auto: yes
  maxwidth: 1200

match:
  strong_rec_thresh: 0.20

musicbrainz:
  search_limit: 10
