apiVersion: v1
kind: Pod
metadata:
  name: zfs-tools
  namespace: kube-system
spec:
  containers:
    - name: zfs-tools
      image: ubuntu:24.04
      command: ["/bin/sh", "-c", "apt update && apt install -y zfsutils-linux smartmontools nvme-cli && sleep infinity"]
      securityContext:
        privileged: true
      volumeMounts:
        - name: host-dev
          mountPath: /dev
  volumes:
    - name: host-dev
      hostPath:
        path: /dev
  hostNetwork: true
  hostPID: true
  restartPolicy: Never
