---
instance:
  distribution:
    # renovate: datasource=github-releases depName=controlplaneio-fluxcd/distribution
    version: 2.7.0
  cluster:
    networkPolicy: false
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  sync:
    kind: GitRepository
    url: "https://github.com/s0len/solen-ops"
    ref: refs/heads/main
    path: kubernetes/flux/cluster
    interval: 1h
  commonMetadata:
    labels:
      app.kubernetes.io/name: flux
  kustomize:
    patches:
      - # Add Sops decryption to 'flux-system' Kustomization
        patch: |
          - op: add
            path: /spec/decryption
            value:
              provider: sops
              secretRef:
                name: sops-age
        target:
          group: kustomize.toolkit.fluxcd.io
          kind: Kustomization
      - # Increase the number of workers
        patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --concurrent=5
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --requeue-dependency=15s
        target:
          kind: Deployment
          name: (kustomize-controller|helm-controller|source-controller)
      - # Increase the memory limits
        patch: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: all
          spec:
            template:
              spec:
                containers:
                  - name: manager
                    resources:
                      limits:
                        memory: 5Gi
        target:
          kind: Deployment
          name: (kustomize-controller|helm-controller|source-controller)
      - # Enable in-memory kustomize builds and add timeout settings
        patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --concurrent=8
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --kube-api-qps=100
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --kube-api-burst=300
          - op: replace
            path: /spec/template/spec/volumes/0
            value:
              name: temp
              emptyDir:
                medium: Memory
        target:
          kind: Deployment
          name: kustomize-controller
      - # Enable Helm repositories caching
        patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --helm-cache-max-size=10
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --helm-cache-ttl=60m
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --helm-cache-purge-interval=5m
        target:
          kind: Deployment
          name: source-controller
      - # Flux near OOM detection for Helm
        patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --feature-gates=OOMWatch=true
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --oom-watch-memory-threshold=95
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --oom-watch-interval=500ms
        target:
          kind: Deployment
          name: helm-controller
