---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app open-webui
  namespace: &namespace ai
spec:
  path: kubernetes/apps/ai/open-webui/app
  targetNamespace: *namespace
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/external
  prune: true
  wait: false
  retryInterval: 2m
  interval: 10m
  dependsOn: []
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: ollama
