---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grimmory
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grimmory-secret
    template:
      data:
        DATABASE_URL: "jdbc:mariadb://localhost:3306/grimmory"
        DATABASE_USERNAME: &dbUser "{{ .GRIMMORY_DATABASE_USER }}"
        DATABASE_PASSWORD: &dbPass "{{ .GRIMMORY_DATABASE_PASS }}"
        MYSQL_ROOT_PASSWORD: "{{ .GRIMMORY_DATABASE_ROOT_PASS }}"
        MYSQL_DATABASE: &dbName grimmory
        MYSQL_USER: *dbUser
        MYSQL_PASSWORD: *dbPass
  dataFrom:
    - extract:
        key: grimmory
      rewrite:
        - regexp:
            source: "(.*)"
            target: "GRIMMORY_$1"
