# Node: control-2
# IP: 192.168.10.42
# Hardware: Intel 13400, Intel A310 GPU, 10G Realtek NIC, 64GB RAM, Samsung 870 EVO SATA SSD
---
machine:
  type: controlplane
---
apiVersion: v1alpha1
kind: LinkConfig
name: enp5s0
mtu: 1500
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: enp5s0
routeMetric: 1024
clientIdentifier: none
---
apiVersion: v1alpha1
kind: VLANConfig
name: enp5s0.20
vlanID: 20
parent: enp5s0
addresses:
  - address: 192.168.20.42/24
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 192.168.10.80
link: enp5s0
---
apiVersion: v1alpha1
kind: KubeNodeConfig
labels:
  intel.feature.node.kubernetes.io/gpu: "true"
  plex.node/preferred: "true"
  topology.kubernetes.io/zone: zone-c
  node.kubernetes.io/storage: ceph
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: system_disk
  grow: true
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: control-2
---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
installer:
  image: "factory.talos.dev/metal-installer/${TALOS_SCHEMATIC}:${TALOS_VERSION}"
provisioning:
  diskSelector:
    match: glob("*SSD 870*", disk.model)
  wipe: false
