---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-controller
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-zfs-64k
