---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zipline
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: zipline-secret
    template:
      data:
        CORE_SECRET: "{{ .ZIPLINE_CORE_SECRET }}"
        DATABASE_URL: "postgres://{{ .ZIPLINE_POSTGRES_USER }}:{{ .ZIPLINE_POSTGRES_PASSWORD }}@postgres16-rw.database.svc.cluster.local/{{ .ZIPLINE_POSTGRES_DB }}"
        INIT_POSTGRES_DBNAME: "{{ .ZIPLINE_POSTGRES_DB }}"
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .ZIPLINE_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .ZIPLINE_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .CNPG_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
      rewrite:
        - regexp:
            source: "(.*)"
            target: "CNPG_$1"
    - extract:
        key: zipline
      rewrite:
        - regexp:
            source: "(.*)"
            target: "ZIPLINE_$1"
