# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/v1.14.2/pkg/machinery/config/schemas/config.schema.json
---
version: v1alpha1
debug: false

machine:
  token: op://talos/talos/MACHINE_TOKEN
  ca:
    crt: op://talos/talos/MACHINE_CA_CRT
    key: op://talos/talos/MACHINE_CA_KEY
  certSANs:
    - 192.168.10.80
    - 127.0.0.1
  logging:
    destinations:
      - endpoint: tcp://192.168.10.122:6051/
        format: json_lines
  kubelet:
    image: "ghcr.io/siderolabs/kubelet:${KUBERNETES_VERSION}"
    extraArgs:
      feature-gates: DynamicResourceAllocation=true
    extraConfig:
      maxPods: 150
      serializeImagePulls: false
      featureGates:
        DynamicResourceAllocation: true
    extraMounts:
      - destination: /var/mnt/local-hostpath
        type: bind
        source: /var/mnt/local-hostpath
        options:
          - bind
          - rshared
          - rw
    defaultRuntimeSeccompProfileEnabled: true
    nodeIP:
      validSubnets:
        - 192.168.10.0/24
    disableManifestsDirectory: true
  files:
    - op: create
      permissions: 493
      path: /var/mnt/local-hostpath/.gitkeep
      content: ""
  features:
    rbac: true
    apidCheckExtKeyUsage: true
    diskQuotaSupport: true

cluster:
  controlPlane:
    endpoint: https://192.168.10.80:6443
  clusterName: main
  network:
    cni:
      name: none
    dnsDomain: cluster.local
    podSubnets:
      - 10.69.0.0/16
    serviceSubnets:
      - 10.96.0.0/16
  token: op://talos/talos/CLUSTER_TOKEN
  secretboxEncryptionSecret: op://talos/talos/CLUSTER_SECRETBOXENCRYPTIONSECRET
  ca:
    crt: op://talos/talos/CLUSTER_CA_CRT
    key: op://talos/talos/CLUSTER_CA_KEY
  aggregatorCA:
    crt: op://talos/talos/CLUSTER_AGGREGATORCA_CRT
    key: op://talos/talos/CLUSTER_AGGREGATORCA_KEY
  serviceAccount:
    key: op://talos/talos/CLUSTER_SERVICEACCOUNT_KEY
  apiServer:
    image: "registry.k8s.io/kube-apiserver:${KUBERNETES_VERSION}"
    extraArgs:
      enable-aggregator-routing: "true"
      feature-gates: ImageVolume=true,MutatingAdmissionPolicy=true
      runtime-config: admissionregistration.k8s.io/v1beta1=true
    certSANs:
      - 192.168.10.80
      - 127.0.0.1
    disablePodSecurityPolicy: true
    auditPolicy:
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
        - level: Metadata
  controllerManager:
    image: "registry.k8s.io/kube-controller-manager:${KUBERNETES_VERSION}"
    extraArgs:
      bind-address: 0.0.0.0
  proxy:
    disabled: true
  scheduler:
    image: "registry.k8s.io/kube-scheduler:${KUBERNETES_VERSION}"
    extraArgs:
      bind-address: 0.0.0.0
  etcd:
    ca:
      crt: op://talos/talos/CLUSTER_ETCD_CA_CRT
      key: op://talos/talos/CLUSTER_ETCD_CA_KEY
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
    advertisedSubnets:
      - 192.168.10.0/24
  coreDNS:
    disabled: true
  allowSchedulingOnControlPlanes: true
---
apiVersion: v1alpha1
kind: KmsgLogConfig
name: remote-log
url: tcp://192.168.10.122:6050/
---
apiVersion: v1alpha1
kind: DiscoveryServiceConfig
name: default
endpoint: https://discovery.talos.dev/
---
apiVersion: v1alpha1
kind: DiscoveryIdentityConfig
clusterID: op://talos/talos/CLUSTER_ID
clusterSecret: op://talos/talos/CLUSTER_SECRET
---
apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
  - address: 1.1.1.1
  - address: 1.0.0.1
searchDomains:
  domains: []
  disableDefault: true
hostDNS:
  enabled: true
  forwardKubeDNSToHost: false
  resolveMemberNames: true
---
apiVersion: v1alpha1
kind: KubePrismConfig
port: 7445
---
apiVersion: v1alpha1
kind: KubeTalosAPIAccessConfig
allowedRoles:
  - os:admin
allowedKubernetesNamespaces:
  - kube-system
  - actions-runner-system
---
apiVersion: v1alpha1
kind: SysctlConfig
params:
  fs.inotify.max_queued_events: "65536"
  fs.inotify.max_user_instances: "8192"
  fs.inotify.max_user_watches: "1048576"
  net.core.bpf_jit_harden: "1"
  net.core.default_qdisc: fq
  net.core.rmem_max: "134217728"
  net.core.wmem_max: "134217728"
  net.core.rmem_default: "134217728"
  net.core.wmem_default: "134217728"
  net.core.optmem_max: "134217728"
  net.core.netdev_max_backlog: "500000"
  net.ipv4.tcp_timestamps: "0"
  net.ipv4.tcp_congestion_control: bbr
  net.ipv4.tcp_fastopen: "3"
  net.ipv4.tcp_max_syn_backlog: "8192"
  net.ipv4.tcp_rmem: 4096 524288 134217728
  net.ipv4.tcp_wmem: 4096 524288 134217728
  net.ipv4.tcp_mtu_probing: "1"
  net.ipv4.tcp_window_scaling: "1"
  sunrpc.tcp_slot_table_entries: "128"
  sunrpc.tcp_max_slot_table_entries: "128"
  user.max_user_namespaces: "11255"
  vm.nr_hugepages: "1024"
---
apiVersion: v1alpha1
kind: SysfsConfig
params:
  devices.system.cpu.intel_pstate.hwp_dynamic_boost: "1"
---
apiVersion: v1alpha1
kind: UdevRulesConfig
rules:
  - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"
---
apiVersion: v1alpha1
kind: EtcFileConfig
name: nfsmount.conf
mode: 0o644
contents: |
  [ NFSMount_Global_Options ]
  hard=True
  nconnect=16
  noatime=True
---
apiVersion: v1alpha1
kind: CRICustomizationConfig
name: spegel-cdi
content: |
  [plugins."io.containerd.cri.v1.images"]
    discard_unpacked_layers = false
  [plugins."io.containerd.cri.v1.runtime"]
    cdi_spec_dirs = ["/var/cdi/static", "/var/cdi/dynamic"]
    device_ownership_from_security_context = true
