---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cross-seed
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: qbittorrent
      namespace: media

  values:
    controllers:
      cross-seed:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/cross-seed/cross-seed
              tag: 6.13.2@sha256:9d55669b92af084ac3487fa717d3a87d7b46781b24a5f0903fff993e82715452
            env:
              TZ: ${TIMEZONE}
            args: ["daemon"]
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 32Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: cross-seed
        ports:
          http:
            port: 80

    persistence:
      config:
        existingClaim: *app

      secret-file:
        type: secret
        name: cross-seed-secret
        globalMounts:
          - path: /config/config.js
            subPath: config.js
            readOnly: true

      data:
        type: nfs
        server: ${TRUENAS_IP}
        path: /mnt/rust/data
        globalMounts:
          - path: /data
            readOnly: false
