---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netronome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: netronome-secret
    template:
      data:
        NETRONOME__DB_HOST: "postgres16-rw.database.svc.cluster.local"
        NETRONOME__DB_PORT: "5432"
        NETRONOME__DB_USER: &dbuser "{{ .NETRONOME_POSTGRES_USER }}"
        NETRONOME__DB_PASSWORD: &dbpass "{{ .NETRONOME_POSTGRES_PASSWORD }}"
        NETRONOME__DB_NAME: &dbname "{{ .NETRONOME_POSTGRES_DB }}"
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .CNPG_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
      rewrite:
        - regexp:
            source: "(.*)"
            target: "CNPG_$1"
    - extract:
        key: netronome
      rewrite:
        - regexp:
            source: "(.*)"
            target: "NETRONOME_$1"
