---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: dragonfly-operator
  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    # serviceMonitor:
    #   enabled: true
    grafanaDashboard:
      enabled: true
  postRenderers:
    - kustomize:
        patches:
          # TODO: remove when upstream fix is released
          # https://github.com/dragonflydb/dragonfly-operator/pull/305
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: dragonfly-operator
              namespace: dragonfly-operator-system
            patch: |
              - op: remove
                path: /spec/template/spec/containers/1/args/0
              - op: remove
                path: /spec/template/spec/containers/1/args/0
