---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tandoor
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      tandoor:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18@sha256:6fa1f331cddd2eb0b6afa7b8d3685c864127a81ab01c3d9400bc3ff5263a51cf
            envFrom: &envFrom
              - secretRef:
                  name: tandoor-secret
        containers:
          app:
            image:
              repository: ghcr.io/tandoorrecipes/recipes
              tag: 2.6.2@sha256:96708d9df195457b3194fcfde2aa4a814f3fe28cbb90d0045789555d0d1e8da6
            env:
              TZ: ${TIMEZONE}
              ALLOWED_HOSTS: "recipes.${SECRET_DOMAIN}"
              COMMENT_PREF_DEFAULT: 1
              DB_ENGINE: django.db.backends.postgresql_psycopg2
              DEBUG: 0
              ENABLE_PDF_EXPORT: 1
              ENABLE_SIGNUP: 0
              FRACTION_PREF_DEFAULT: 0
              GUNICORN_MEDIA: 0
              SHOPPING_MIN_AUTOSYNC_INTERVAL: 5
            envFrom: *envFrom
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1024Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
    route:
      app:
        hostnames:
          - "recipes.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: http
    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          tandoor:
            app:
              - path: /opt/recipes/mediafiles
                subPath: mediafiles
              - path: /opt/recipes/staticfiles
                subPath: staticfiles
      tmp:
        type: emptyDir
        advancedMounts:
          tandoor:
            app:
              - path: /opt/recipes/cookbook/static/django_js_reverse
                subPath: django_js_reverse
              - path: /var/lib/nginx/logs
                subPath: logs
              - path: /tmp
                subPath: tmp
