---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbitmanage
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: qbittorrent
      namespace: media

  values:
    controllers:
      qbitmanage:
        type: cronjob
        cronjob:
          schedule: "*/30 * * * *"
          timeZone: &timeZone ${TIMEZONE}
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          app:
            image:
              repository: ghcr.io/stuffanthings/qbit_manage
              tag: v4.5.5@sha256:5b116736a7ec6d8921f3c906ebbe6da41f60348389f43acd30a720bdd2531e08
            env:
              TZ: *timeZone
              QBT_CONFIG: "/config/config.yaml"
              QBT_CAT_UPDATE: false
              QBT_CROSS_SEED: false
              QBT_DIVIDER: "="
              QBT_DRY_RUN: false
              QBT_LOG_LEVEL: INFO
              QBT_RECHECK: true
              QBT_REM_ORPHANED: true
              QBT_REM_UNREGISTERED: true
              QBT_RUN: true
              QBT_SHARE_LIMITS: false
              QBT_SKIP_CLEANUP: false
              QBT_SKIP_QB_VERSION_CHECK: true
              QBT_TAG_NOHARDLINKS: true
              QBT_TAG_TRACKER_ERROR: true
              QBT_TAG_UPDATE: true
              QBT_WIDTH: 300
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            lifecycle:
              postStart:
                exec:
                  command:
                    [
                      "/bin/sh",
                      "-c",
                      "cp /secret/config.yaml /config/config.yaml",
                    ]

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch

    persistence:
      app:
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /app/config
          - path: /config
          - path: /tmp

      config-file:
        type: secret
        name: qbitmanage-secret
        globalMounts:
          - path: /secret/config.yaml
            subPath: config.yaml
            readOnly: true

      data:
        type: nfs
        server: ${TRUENAS_IP}
        path: /mnt/rust/data/torrents
        globalMounts:
          - path: /data/torrents

      qbittorrent:
        existingClaim: qbittorrent
        globalMounts:
          - path: /qbittorrent
            readOnly: true
