---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kanidm-client-autobrr
  namespace: security
  labels:
    kanidm_config: "1"
data:
  targetNamespace: media
  client.json: |
    {
      "systems": {
        "oauth2": {
          "autobrr": {
            "displayName": "autobrr",
            "originUrl": "https://autobrr.uniflix.vip/api/auth/oidc/callback",
            "originLanding": "https://autobrr.uniflix.vip/",
            "preferShortUsername": true,
            "scopeMaps": {
              "users": ["openid", "profile", "email", "groups"]
            },
            "k8s": {}
          }
        }
      }
    }
