---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kanidm-client-nextcloud
  namespace: security
  labels:
    kanidm_config: "1"
data:
  targetNamespace: default
  client.json: |
    {
      "systems": {
        "oauth2": {
          "nextcloud": {
            "displayName": "Nextcloud",
            "originUrl": "https://cloud.uniflix.vip/apps/oidc_login/oidc",
            "originLanding": "https://cloud.uniflix.vip/",
            "preferShortUsername": true,
            "scopeMaps": {
              "users": ["openid", "profile", "email", "groups"]
            },
            "k8s": {}
          }
        }
      }
    }
