---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kanidm-client-paperless
  namespace: security
  labels:
    kanidm_config: "1"
data:
  targetNamespace: default
  client.json: |
    {
      "systems": {
        "oauth2": {
          "paperless": {
            "displayName": "Paperless-ngx",
            "originUrl": "https://paperless.uniflix.vip/accounts/oidc/kanidm/login/callback/",
            "originLanding": "https://paperless.uniflix.vip/",
            "preferShortUsername": true,
            "scopeMaps": {
              "users": ["openid", "profile", "email", "groups"]
            },
            "k8s": {}
          }
        }
      }
    }
