---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui
  namespace: ai
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-zfs-1m
