apiVersion: apps/v1
kind: Deployment
metadata:
  name: intel-gpu-exporter
  namespace: observability
  labels:
    app.kubernetes.io/name: intel-gpu-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: intel-gpu-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: intel-gpu-exporter
    spec:
      containers:
        - name: intel-gpu-exporter
          image: ghcr.io/onedr0p/intel-gpu-exporter:rolling
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
              name: metrics
          volumeMounts:
            - mountPath: /dev/dri
              name: dri
      volumes:
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: intel-gpu-exporter
  namespace: observability
  labels:
    app.kubernetes.io/name: intel-gpu-exporter
spec:
  selector:
    app.kubernetes.io/name: intel-gpu-exporter
  ports:
    - port: 8080
      targetPort: metrics
      name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: intel-gpu-exporter
  namespace: observability
  labels:
    app.kubernetes.io/name: intel-gpu-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: intel-gpu-exporter
  endpoints:
    - port: metrics
      interval: 30s
