# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

###################################################################################################
# Recyclarr Configuration: Updated to new template structure                                     #
# Updated: 2025-01-XX                                                                           #
# Documentation: https://recyclarr.dev                                                            #
###################################################################################################

# Configuration specific to Sonarr
sonarr:
  sonarr:
    # Set the URL/API Key to your actual instance
    base_url: http://sonarr.media.svc.cluster.local
    api_key: !env_var SONARR_API_KEY

    delete_old_custom_formats: true
    replace_existing_custom_formats: false

    media_naming:
      series: plex-tvdb
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    include:
      # Standard Web profiles
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p
      - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-custom-formats-web-2160p
      # Anime profiles
      - template: sonarr-quality-definition-anime
      - template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime

    quality_definition:
      type: series

    # Custom formats for specific configurations
    custom_formats:
      # Swedish content for kids profile
      - trash_ids:
          - eb3d5cc0a2be0db205fb823640db6a3c # Not Swedish
        assign_scores_to:
          - name: Swedish
            score: 6

      # Optional formats that were previously in external configs
      - trash_ids:
          # - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          # - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          # - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          # - 06d66ab109d4d2eddb2794d21526d140 # Retags
          # - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-1080p
          - name: WEB-2160p

      - trash_ids:
          # Allow x265 HD releases
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        assign_scores_to:
          - name: Swedish
            score: 0
      - trash_ids:
          - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
          - name: Swedish

    quality_profiles:
      # Custom Swedish profile for kids content
      - name: Swedish
        reset_unmatched_scores:
          enabled: true
          except:
            - Not Swedish
        qualities:
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
          - name: Bluray-1080p
          - name: HDTV-1080p
          - name: WEB 720p
            qualities:
              - WEBRip-720p
              - WEBDL-720p
          - name: HDTV-720p

# Configuration specific to Radarr.
radarr:
  radarr-anime:
    # Set the URL/API Key to your actual instance
    base_url: http://radarr-anime.media.svc.cluster.local
    api_key: !env_var RADARR_API_KEY

    delete_old_custom_formats: true
    replace_existing_custom_formats: false

    # Media Naming Configuration
    media_naming:
      folder: plex-tmdb
      movie:
        rename: true
        standard: plex-anime-tmdb

    include:
      # Use new anime templates
      - template: radarr-quality-definition-anime
      - template: radarr-quality-profile-anime
      - template: radarr-custom-formats-anime

    quality_definition:
      type: movie

    # Custom formats for anime-specific adjustments
    custom_formats:
      - trash_ids:
          - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired

      - trash_ids:
          - a5d148168c4506b55cf53984107c396e # 10bit
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired

      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired

  radarr-standard:
    base_url: http://radarr-standard.media.svc.cluster.local
    api_key: !env_var RADARR_API_KEY

    replace_existing_custom_formats: true
    delete_old_custom_formats: true

    # Media Naming Configuration
    media_naming:
      folder: plex-tmdb
      movie:
        rename: true
        standard: plex-tmdb

    include:
      # Use new SQP templates
      - template: radarr-quality-definition-sqp-uhd
      - template: radarr-quality-profile-sqp-2
      - template: radarr-custom-formats-sqp-2
      - template: radarr-quality-profile-sqp-3
      - template: radarr-custom-formats-sqp-3
      - template: radarr-quality-profile-sqp-4
      - template: radarr-custom-formats-sqp-4

    quality_definition:
      type: sqp-uhd

    quality_profiles:
      - name: SQP-2
        reset_unmatched_scores:
          enabled: true
          # except:
          #   - "!Personal LQ list"

      # Custom quality profile as we follow 'SQP-3 (Audio)'
      # https://discord.com/channels/492590071455940612/1385343352563826748
      - name: SQP-3
        reset_unmatched_scores:
          enabled: true
          except:
            - "!Personal LQ list"
        upgrade:
          allowed: true
          until_quality: WEB|Remux|2160p
          until_score: 10000
        min_format_score: 3350
        score_set: sqp-3
        quality_sort: top
        qualities:
          - name: WEB|Remux|2160p
            qualities:
              - Remux-2160p
              - WEBDL-2160p
              - WEBRip-2160p
              - Remux-1080p

      - name: SQP-4
        reset_unmatched_scores:
          enabled: true
          # except:
          #   - "!Personal LQ list"

    # Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # Movie Versions
      # Uncomment any of the following lines to prefer these movie versions
      - trash_ids:
          - 0f12c086e289cf966fa5948eac571f44 # Hybrid
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - eecf3a857724171f968a66cb5719e152 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        assign_scores_to:
          - name: SQP-3

      # Misc
      - trash_ids:
          - 2899d84dc9372de3408e6d8cc18e9666 # x264
        assign_scores_to:
          - name: SQP-3
            # score: 0 # Uncomment this line to enable x264 releases

      # Unwanted
      - trash_ids:
          # Uncomment the next six lines to block all x265 HD releases
          - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
        assign_scores_to:
          - name: SQP-3
            score: 0
      - trash_ids:
          - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
        assign_scores_to:
          - name: SQP-3

      # Optional
      - trash_ids:
          # HDR10+ Boost - Uncomment the HDR10+ Boost line if you want to prefer HDR10+ releases
          # DV Boost - Uncomment the DV Boost line if you want to prefer DV releases
          # Uncomment both lines if you want to prefer both (DV HDR10+)
          - b337d6812e06c200ec9a2d3cfa9d20a7 # DV Boost
          # - caa37d0df9c348912df1fb1d88f9273a # HDR10+ Boost

          # Comment out the next line if you and all of your users' setups are fully DV compatible
          - 923b6abef9b17f937fab56cfcf89e1f1 # DV (WEBDL)

          # Uncomment any of the following if you want them to be added to the quality profile
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
          - f700d29429c023a5734505e77daeaea7 # DV (Disk)
        assign_scores_to:
          - name: SQP-3

      # Optional SDR
      # Only ever use ONE of the following custom formats:
      # SDR - block ALL SDR releases
      # SDR (no WEBDL) - block UHD/4k Remux and Bluray encode SDR releases, but allow SDR WEB
      - trash_ids:
          - 9c38ebb7384dada637be8899efa68e6f # SDR
          # - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL)
        assign_scores_to:
          - name: SQP-3

      # Release groups with some extra points
      - trash_ids:
          - 5153ec7413d9dae44e24275589b5e944 # BHDStudio
          - e098247bc6652dd88c76644b275260ed # FLUX
          - ff5bc9e8ce91d46c997ca3ac6994d6f8 # FraMeSToR
          - 7a0d1ad358fee9f5b074af3ef3f9d9ef # hallowed
          - d66d26d37c32b0137cd26f42abaa7c2e # TheFarm
        assign_scores_to:
          - name: SQP-3

  radarr-kids:
    base_url: http://radarr-kids.media.svc.cluster.local
    api_key: !env_var RADARR_API_KEY

    delete_old_custom_formats: true
    replace_existing_custom_formats: false

    # Media Naming Configuration
    media_naming:
      folder: plex-tmdb
      movie:
        rename: true
        standard: plex-tmdb

    include:
      # Use new SQP-1 templates for kids content
      - template: radarr-quality-definition-sqp-streaming
      - template: radarr-quality-profile-sqp-1
      - template: radarr-custom-formats-sqp-1

    quality_definition:
      type: sqp-streaming

    quality_profiles:
      - name: SQP-1 (1080p)
        # Uncomment the below line if you don't have access to top-tier indexers
        min_format_score: 0
        reset_unmatched_scores:
          enabled: true
          except:
            - Not Swedish

      - name: SQP-1 (2160p)
        min_format_score: 0
        reset_unmatched_scores:
          enabled: true
          except:
            - Not Swedish

    # Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # Movie Versions
      - trash_ids:
          # Uncomment the next line if you prefer WEBDL with IMAX Enhanced to BHDStudio
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced

          # Optional - uncomment any of the following if you want them added to your profile
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          # - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          # - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - name: SQP-1 (1080p)

      - trash_ids:
          # Uncomment any of the next six lines to prefer these movie versions
          # - 570bc9ebecd92723d2d21500f4be314c # Remaster
          # - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          # - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          # - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          # - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          # - 957d0f44b592285f26449575e8b1167e # Special Edition
          # Uncomment the next line if you prefer 1080p/2160p WEBDL with IMAX Enhanced
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        assign_scores_to:
          - name: SQP-1 (2160p)
      - trash_ids:
          # Uncomment the next two lines if you have a setup that supports HDR10+
          - b17886cb4158d9fea189859409975758 # HDR10+ Boost
          - 55a5b50cb416dea5a50c4955896217ab # DV HDR10+ Boost

          # Uncomment any of the following optional custom formats if you want them to be added to
          # the quality profile
          # - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          # - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          # - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          # - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          # - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          # - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          # - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - name: SQP-1 (2160p)
