# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# A starter config to use with Recyclarr. Most values are set to "reasonable defaults". Update the
# values below as needed for your instance. You will be required to update the API Key and URL for
# each instance you want to use.
#
# Many optional settings have been omitted to keep this template simple. Note that there's no "one
# size fits all" configuration. Please refer to the guide to understand how to build the appropriate
# configuration based on your hardware setup and capabilities.
#
# For any lines that mention uncommenting YAML, you simply need to remove the leading hash (`#`).
# The YAML comments will already be at the appropriate indentation.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://recyclarr.dev/wiki/yaml/config-reference/

# Configuration specific to Sonarr
sonarr:
  sonarr:
    # Set the URL/API Key to your actual instance
    base_url: http://sonarr.media.svc.cluster.local
    api_key: !env_var SONARR_API_KEY

    delete_old_custom_formats: true
    replace_existing_custom_formats: false

    media_naming:
      series: plex
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    include:
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p
      - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-custom-formats-web-2160p
      - template: sonarr-quality-definition-series
      - config: Sonarr_Anime_Quality_Profiles.yaml
      - config: Sonarr_Anime_Custom_Formats.yaml
      - config: Sonarr_Standard_Quality_Profiles.yaml
      - config: Sonarr_Standard_Custom_Formats.yaml
      - config: Sonarr_Kids_Quality_Profiles.yaml
      - config: Sonarr_Kids_Custom_Formats.yaml

    quality_definition:
      type: series

# Configuration specific to Radarr.
radarr:
  radarr-anime:
    # Set the URL/API Key to your actual instance
    base_url: http://radarr-anime.media.svc.cluster.local
    api_key: !env_var RADARR_API_KEY

    delete_old_custom_formats: true
    replace_existing_custom_formats: false

    # Media Naming Configuration
    media_naming:
      folder: plex
      movie:
        rename: true
        standard: anime

    # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'
    quality_definition:
      type: movie

    quality_profiles:
      - name: Anime
        reset_unmatched_scores:
          enabled: true
          # except:
          #   - "!Personal LQ list"
        qualities:
          - name: Remux-1080p
            qualities:
              - Bluray-1080p
              - Remux-1080p
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
              - HDTV-1080p
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - WEBRip-720p
              - WEBDL-720p
              - HDTV-720p
          - name: Bluray-576p
          - name: Bluray-480p
          - name: WEB 480p
            qualities:
              - WEBRip-480p
              - WEBDL-480p

    custom_formats:
      - trash_ids:
          - fb3ccc5d5cc8f77c9055d4cb4561dded # Anime BD T1
          - 66926c8fa9312bc74ab71bf69aae4f4a # Anime BD T2
          - fa857662bad28d5ff21a6e611869a0ff # Anime BD T3
          - f262f1299d99b1a2263375e8fa2ddbb3 # Anime BD T4
          - ca864ed93c7b431150cc6748dc34875d # Anime BD T5
          - 9dce189b960fddf47891b7484ee886ca # Anime BD T6
          - 1ef101b3a82646b40e0cab7fc92cd896 # Anime BD T7
          - 6115ccd6640b978234cc47f2c1f2cadc # Anime BD T8
          - 8167cffba4febfb9a6988ef24f274e7e # Anime Web Tier 01
          - 8526c54e36b4962d340fce52ef030e76 # Anime Web Tier 02
          - de41e72708d2c856fa261094c85e965d # Anime Web Tier 03
          - 9edaeee9ea3bcd585da9b7c0ac3fc54f # Anime Web Tier 04
          - 22d953bbe897857b517928f3652b8dd3 # Anime Web Tier 05
          - a786fbc0eae05afe3bb51aee3c83a9d4 # Anime Web Tier 06
          - 3a3ff47579026e76d6504ebea39390de # Remux Tier 01
          - 9f98181fe5a3fbeb0cc29340da2a468a # Remux Tier 02
          - 8baaf0b3142bf4d94c42a724f034e27a # Remux Tier 03
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 01
          - 06b6542a47037d1e33b15aa3677c2365 # Anime Raws
          - b0fdc5897f68c9a68c70c25169f77447 # Anime LQ Groups
          - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
          - c259005cbaeb5ab44c06eddb4751e70c # v0
          - 5f400539421b8fcf71d51e6384434573 # v1
          - 3df5e6dfef4b09bb6002f732bed5b774 # v2
          - db92c27ba606996b146b57fbe6d09186 # v3
          - d4e5e842fad129a3c097bdb2d20d31a0 # v4
          - 60f6d50cbd3cfc3e9a8c00e3a30c3114 # VRV
          - a5d148168c4506b55cf53984107c396e # 10bit
          - 4a3b087eea2ce012fcc1ce319259a3be # Dual Audio
          - b23eae459cc960816f2d6ba84af45055 # Dubs Only
          - 9172b2f683f6223e3a1846427b417a3d # VOSTFR
        assign_scores_to:
          - name: Anime

  radarr-standard:
    base_url: http://radarr-standard.media.svc.cluster.local
    api_key: !env_var RADARR_API_KEY

    delete_old_custom_formats: true
    replace_existing_custom_formats: false

    quality_definition:
      type: sqp-uhd

    # Media Naming Configuration
    media_naming:
      folder: plex
      movie:
        rename: true
        standard: default

    include:
      - template: radarr-quality-definition-sqp-uhd

      - template: radarr-quality-profile-sqp-2
      - template: radarr-quality-profile-sqp-3
      - template: radarr-quality-profile-sqp-4

      - template: radarr-custom-formats-sqp-2
      - template: radarr-custom-formats-sqp-3
      - template: radarr-custom-formats-sqp-4

    quality_profiles:
      - name: SQP-2
        reset_unmatched_scores:
          enabled: true
          # except:
          #   - "!Personal LQ list"
      - name: SQP-3 # custom as we moved remux-1080p into the `WEB|Remux|2160p` TRaSH calls it `SQP-3 (audio)`
        reset_unmatched_scores:
          enabled: true
          # except:
          #   - "!Personal LQ list"
        min_format_score: 3350
        qualities:
          - name: WEB|Remux|2160p
            qualities:
              - WEBDL-2160p
              - WEBRip-2160p
              - Remux-2160p
              - WEBDL-1080p
              - WEBRip-1080p
              - Remux-1080p
      - name: SQP-4
        reset_unmatched_scores:
          enabled: true
          # except:
          #   - "!Personal LQ list"

    # Custom scoring on top of templates above
    custom_formats:
      # Add some specific release groups bumps as we prefer them over others
      - trash_ids:
          - 5153ec7413d9dae44e24275589b5e944 # BHDStudio
          - 7a0d1ad358fee9f5b074af3ef3f9d9ef # hallowed
          - e098247bc6652dd88c76644b275260ed # FLUX
          - ff5bc9e8ce91d46c997ca3ac6994d6f8 # FRAMESTOR
        assign_scores_to:
          - name: SQP-2
          - name: SQP-3
          - name: SQP-4

      # Uncomment any of the following if you want them to be added to the quality profile
      - trash_ids:
          # Movie Versions
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
          # Misc
          - 2899d84dc9372de3408e6d8cc18e9666 # x264
          # Unwanted
          - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
          # Optional
          - b17886cb4158d9fea189859409975758 # HDR10+ Boost
          - 55a5b50cb416dea5a50c4955896217ab # DV HDR10+ Boost
          - 923b6abef9b17f937fab56cfcf89e1f1 # DV (WEBDL)
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          # - f537cf427b64c38c8e36298f657e4828 # Scene
          - f700d29429c023a5734505e77daeaea7 # DV (Disk)
          - cae4ca30163749b891686f95532519bd # AV1
          - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL)
        assign_scores_to:
          - name: SQP-2
          - name: SQP-3
          - name: SQP-4

      - trash_ids:
          - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
        assign_scores_to:
          - name: SQP-2
            score: 0
          - name: SQP-3
            score: 0
          - name: SQP-4
            score: 0

  radarr-kids:
    base_url: http://radarr-kids.media.svc.cluster.local
    api_key: !env_var RADARR_API_KEY

    delete_old_custom_formats: true
    replace_existing_custom_formats: false

    quality_definition:
      type: sqp-streaming

    # Media Naming Configuration
    media_naming:
      folder: plex
      movie:
        rename: true
        standard: default

    quality_profiles:
      - name: SQP-1 (1080p)
        # Uncomment the below line if you don't have access to top-tier indexers
        min_format_score: 0
        reset_unmatched_scores:
          enabled: true
          except:
            - Not Swedish

      - name: SQP-1 (2160p)
        min_format_score: 0
        reset_unmatched_scores:
          enabled: true
          except:
            - Not Swedish

    include:
      # Comment out any of the following includes to disable them
      - template: radarr-quality-definition-sqp-streaming
      - template: radarr-quality-profile-sqp-1-1080p
      - template: radarr-custom-formats-sqp-1-1080p
      - template: radarr-quality-profile-sqp-1-2160p-imax-e
      - template: radarr-custom-formats-sqp-1-2160p

    # Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # Movie Versions
      - trash_ids:
          # Uncomment the next line if you prefer WEBDL with IMAX Enhanced to BHDStudio
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced

          # Optional - uncomment any of the following if you want them added to your profile
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          # - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          # - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - name: SQP-1 (1080p)

      - trash_ids:
          # Uncomment any of the next six lines to prefer these movie versions
          # - 570bc9ebecd92723d2d21500f4be314c # Remaster
          # - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          # - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          # - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          # - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          # - 957d0f44b592285f26449575e8b1167e # Special Edition
          # Uncomment the next line if you prefer 1080p/2160p WEBDL with IMAX Enhanced
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        assign_scores_to:
          - name: SQP-1 (2160p)
      - trash_ids:
          # Uncomment the next two lines if you have a setup that supports HDR10+
          - b17886cb4158d9fea189859409975758 # HDR10+ Boost
          - 55a5b50cb416dea5a50c4955896217ab # DV HDR10+ Boost

          # Uncomment any of the following optional custom formats if you want them to be added to
          # the quality profile
          # - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          # - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          # - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          # - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          # - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          # - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          # - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - name: SQP-1 (2160p)
